--- #YAML:1.0
name:         Math-Cephes
version:      0.47
version_from: lib/Math/Cephes.pm
installdirs:  site
distribution_type: module
licence:      perl
abstract:     perl interface to the cephes math library
authored_by:
    - Randy Kobes <r.kobes@uwinnipeg.ca>
provides:
    Math::Cephes:
        file: lib/Math/Cephes.pm
        version: 0.47
    Math::Cephes::Complex:
        file: lib/Math/Cephes/Complex.pm
        version: 0.47
    Math::Cephes::Polynomial:
        file: lib/Math/Cephes/Polynomial.pm
        version: 0.47
    Math::Cephes::Matrix:
        file: lib/Math/Cephes/Matrix.pm
        version: 0.47
    Math::Cephes::Fraction:
        file: lib/Math/Cephes/Fraction.pm
        version: 0.47
generated_by: Randy Kobes
urls:
   license: http://dev.perl.org/licenses/
resources:
  license: http://dev.perl.org/licenses/
  homepage: http://cpan-search.svn.sourceforge.net/viewvc/cpan-search/Math-Cephes
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Math-Cephes
  AnnoCPAN: http://annocpan.org/dist/Math-Cephes
  CPANForum: http://www.cpanforum.com/dist/Math-Cephes
  CPANTS: http://cpants.perl.org/dist/Math-Cephes
  Rating: http://cpanratings.perl.org/d/Math-Cephes
  SearchCPAN: http://search.cpan.org/~RKOBES/Math-Cephes/
  Testers: http://cpantesters.perl.org/show/Math-Cephes.html
  UWinnipeg: http://cpan.uwinnipeg.ca/dist/Math-Cephes
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
